CREATE DATABASE `s168308_Project`;
USE `s168308_Project`;

CREATE TABLE `Film` (
	id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    Length INTEGER NOT NULL,
    Locatie VARCHAR(100) NULL,
    summary TEXT NOT NULL
);
CREATE TABLE `concert` (
	id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    Length INTEGER NOT NULL,
    Locatie VARCHAR(100) NULL,
    summary TEXT NOT NULL
);
CREATE TABLE `musical` (
	id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    Length INTEGER NOT NULL,
    Locatie VARCHAR(100) NULL,
    summary TEXT NOT NULL
);
CREATE TABLE `event` (
	id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    Length INTEGER NOT NULL,
    Locatie VARCHAR(100) NULL,
    summary TEXT NOT NULL
);

